---
title: "Exercise 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(colorspace)
library(ggthemes)
library(esquisse)
library(harrypotter)
library(ggtext)
library(ggbeeswarm)
```


```{r load_data}

# Filme von 1970 bis 2020, wenig Informationen pro Film
raw_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
# Filme von 1970 bis 2013, viele Informationen, viele Informationen pro Film

movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')
```

```{r}
hcl_palettes(type = "qualitative", plot = T, n = 9)
hcl_palettes("sequential (single-hue)", n = 7, plot = TRUE)
```

```{r}

plot1 <- movies %>%
 filter(decade_code != "NA") %>%
  ggplot(aes(x = as_factor(decade_code), y = imdb_rating, color = binary, group = as_factor(binary))) +
  geom_quasirandom(dodge.width = .7, width = .15, alpha = .6) +
  scale_color_hp_d(option = "LunaLovegood", name = "Bechdel Status") +
  theme_minimal() +
  labs(
    y = "IMDB Rating",
    x = "Dekade"
     ) +
    theme(
    panel.grid.minor = element_blank(),
    plot.title.position = "plot",
    plot.caption.position = "plot"
  )

plot1

```

```{r}
plot2 <-raw_bechdel %>% 
  filter(between(year, 1970,2013)) %>%
  ggplot() +
  aes(x = year, y =  as.numeric(rating), color = rating) +
  geom_point() +
  geom_jitter() +
  theme_minimal() +
  
  labs(x = "Jahr", y = "Bechdelwert")
  
plot2
```


```{r}

library(patchwork)

(plot2 + plot1) +
  plot_annotation(title = "Filme, die den Bechdel-Test bestehen und nicht bestehen, haben ähnliche IMDB-Bewertungen", subtitle="Vergleich von IMDB_Rating und Bechdel Test")
```



