---
title: "Netflix Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')  %>% 
  separate(duration, c("duration", "duration_units"), " ", convert = TRUE)



# Jeden Eintrag mehrfach listen für jede Kategorie einmal
netflix_titles %>% separate_rows(listed_in, sep = ", ")

# Jeden Eintrag mehrfach listen für jeden Schauspieler einmal
netflix_titles %>% separate_rows(cast, sep = ", ")


```






# Unsere Bearbeitung kommt hier hin

```{r}
```



# Ihre Bearbeitung kommt hier hin

```{r}


#Netflix Content - Movies vs. TV Shows
ggplot(data = netflix_titles, aes(x=type, fill=type))+ 
  geom_bar(color="red", size=0.4, fill="dark red")+
  labs(title ="Netflix content - Movies vs. TV Shows",x= "Content",     y="Amount")


```


```{r}
#Top 10 countries
top_ten<- netflix_titles%>% 
  filter(country != "")%>%
  group_by(country)%>%
  summarise(Total=n())%>%
  arrange(desc(Total)) %>% 
  head(10)

 ggplot(top_ten, aes(x = Total, y = reorder(country, Total))) +
  geom_col(color = "red", fill ="red", alpha = 0.5, width = 0.5) +
  labs(x = "Total Film",y="Country", title = "Rank of Country on Netflix")
 
```






