---
title: "Netflix Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')  %>% 
  separate(duration, c("duration", "duration_units"), " ", convert = TRUE)



# Jeden Eintrag mehrfach listen für jede Kategorie einmal
netflix_titles %>% separate_rows(listed_in, sep = ", ")

# Jeden Eintrag mehrfach listen für jeden Schauspieler einmal
netflix_titles %>% separate_rows(cast, sep = ", ")


```






# Unsere Bearbeitung kommt hier hin

```{r}
```



# Ihre Bearbeitung kommt hier hin

```{r}

netflix_titles %>% 
  filter(release_year > "1980") %>% 
  ggplot(aes(release_year, fill=type))+
  geom_bar(position = "dodge")+
  #facet_wrap(vars(type))+
  scale_x_continuous(breaks = seq(1980, 2020, 5), expand = c(0.05,0))+
  scale_y_continuous(breaks = seq(0, 900, 100), limits = c(0, 800))+
  labs(title = "Anzahl Filme vs. Fernsehsendungen auf Netflix von 1980 bis heute", x= "Erscheinungsjahr", y="Anzahl" )+
  theme_minimal()

#Zoom in
netflix_titles %>% 
  filter(release_year > "2009") %>% 
  ggplot(aes(release_year, fill=type))+
  geom_bar(position = "dodge")+
  #facet_wrap(vars(type))+
  scale_x_continuous(breaks = seq(2010, 2021, 1), expand = c(0,0), limits = c(2009, 2022))+
  scale_y_continuous(breaks = seq(0, 900, 100), limits = c(0, 800))+
  labs(title = "Anzahl Filme vs. Fernsehsendungen auf Netflix von 2010 bis heute", x= "Erscheinungsjahr", y="Anzahl" )+
  theme_minimal()


  
netflix_titles %>% 
   filter(release_year > "2009") %>% 
  filter(country==  c("Germany", "United States")) %>% 
  ggplot(aes(release_year, fill=country))+
  geom_bar(position = "dodge")


netflix_titles %>% 
   filter(release_year > "2009") %>% 
  filter(country==  c("Germany", "United States")) %>% 
  ggplot(aes(release_year, type, color=country))+
  geom_jitter()+
  theme_minimal()
```
