---
title: "Netflix Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')  %>% 
  separate(duration, c("duration", "duration_units"), " ", convert = TRUE)



# Jeden Eintrag mehrfach listen für jede Kategorie einmal
netflix_titles %>% separate_rows(listed_in, sep = ", ")

# Jeden Eintrag mehrfach listen für jeden Schauspieler einmal
netflix_titles %>% separate_rows(cast, sep = ", ")


```






# Unsere Bearbeitung kommt hier hin

```{r}
```



# Ihre Bearbeitung kommt hier hin

```{r}
netflix_titles %>%
  filter(release_year >= 1970) %>%
  #filter(release_year == 1970:1980) %>%
ggplot(aes(x = release_year, fill = type))+
  geom_bar(position = "dodge", width = 0.7) +
  labs(x = "year", y = "count of movies/TV-shows") +
  #scale_x_continuous(limits =c(1970,1980, 1990)) 
  scale_x_continuous(breaks=c(1970, 1980, 1990, 2000, 2010, 2020))

```


