---
title: "Exercise 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(colorspace)
library(ggthemes)
library(ggtext)
library(ggforce)
library(ggdist)
```


```{r load_data}

# Filme von 1970 bis 2020, wenig Informationen pro Film
raw_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
# Filme von 1970 bis 2013, viele Informationen, viele Informationen pro Film

movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')
```

```{r}
hcl_palettes(type = "qualitative", plot = T, n = 9)
hcl_palettes("sequential (single-hue)", n = 7, plot = TRUE)
hcl_palettes(type= )
```



```{r}

movies %>% filter(metascore != "NA", year==1970:2013) %>% ggplot() +
  aes(x = year, y =  as.numeric(metascore), color=binary) +
  geom_point() +
  geom_jitter() +
  labs(title="", subtitle="Evaluation of movies across the years", caption="Evaluation by metacritic.com",x="Year of publication",y="Metascore (0-100)") -> plot_1

movies %>% filter(budget != "NA", year==1970:2013) %>% ggplot() +
  aes(x = year, y =  as.numeric(budget), group = year, color=binary) +
  geom_col() +
  labs(title="", subtitle="Movie budgets across the years",x="Year of publication",y="Budget in $") -> plot_2
  

library(patchwork)

(plot_1 + plot_2) +
  plot_annotation(title = "Neither rating nor budget seem to affect the outcome of the Bechdel test")

```

```{r}
movies %>% filter(metascore != "NA", year==1970:2013) %>% ggplot() +
  aes(x = year, y =  as.numeric(metascore), color=metascore) +
  geom_point() +
  theme_dark() +
  coord_cartesian(clip = 'off')+
  scale_y_continuous(limits=c(0,100))+
  scale_color_continuous_sequential(palette = "teal", rev=FALSE) +
  labs(title="", subtitle="Movie Evaluation Metacritic", caption="Evaluation by metacritic.com",x="Year of publication",y=NULL) -> plot_1

movies %>% filter(imdb_rating != "NA", year==1970:2013) %>% ggplot() +
  aes(x = year, y =  as.numeric(imdb_rating), group = year, color=imdb_rating) +
  geom_point() +
  theme_dark() +
  coord_cartesian(clip = 'off')+
  scale_y_continuous(limits=c(0,10)) +
  scale_color_continuous_sequential(palette = "reds", rev=FALSE) +
  labs(title="", subtitle="Movie Evaluation IMDB", caption="Evaluation by imdb.com", x="Year of publication", y=NULL) -> plot_2

movies %>% filter(metascore != "NA", year==1970:2013) %>% ggplot() +
  aes(x = year, y =  as.numeric(metascore), color=binary) +
  geom_point() +
  theme_dark() +
  coord_cartesian(clip = 'off')+
  scale_y_continuous(limits=c(0,100)) +
  labs(title="", subtitle="Movie Evaluation Metacritic",x="Year of publication",y="Metascore (0-100)") -> plot_3

movies %>% filter(imdb_rating != "NA", year==1970:2013) %>% ggplot() +
  aes(x = year, y =  as.numeric(imdb_rating), color=binary) +
  geom_point() +
  theme_dark() +
  coord_cartesian(clip = 'off')+
  scale_y_continuous(limits=c(0,10)) +
  labs(title="", subtitle="Movie Evaluation IMDB",x="Year of publication",y="IMDB score (0-10)") -> plot_4
  

library(patchwork)

(plot_1 + plot_3 + plot_2 + plot_4 ) +
  plot_annotation(title = "Movie Ratings don't seem to affect the bechdel test")

```




