---
title: "Exercise_02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(gganimate)
library(gifski)
climate_data <- read_csv("../../datasets/climate_monthly.csv")
```


```{r, include=FALSE}
climate_data %>% 
  filter(Source == "GISTEMP") %>% 
  mutate(year = year(Date),
         month = month(Date)) %>% 
  ggplot() +
  aes(x = month, y = Mean, color = Mean, group = year) +
  geom_line() +
  coord_polar() +
  scale_x_continuous(limits = c(0,12), breaks = 1:12) +
  geom_hline(yintercept = 0, color = "white", size = 2) +
  scale_color_viridis_c(option = "B") +
  gganimate::transition_reveal(year) +
  labs(title = "Temperatur im Jahr: {frame_along}") -> anim


animate(
  anim,
  fps = 4,
  nframes = 137, 
  renderer = gifski_renderer()
)


```

























```{r, include=FALSE}


climate_data %>% 
  filter(Source == "GISTEMP") %>% 
  mutate(year = year(Date),
         month = month(Date)) %>%
  ggplot() +
  aes(x = month, y = Mean, group = year, color = year) +
  geom_line() +
  scale_x_continuous(limits = c(0,12), breaks = 1:12) +
  scale_color_gradient(low = "#00FF00", high = "#FF0000") +
  coord_polar(start = 0, theta = "x") +
  gganimate::transition_time(year) +
  labs(title = "Temperatur {frame_time}") +
  exit_fade() +
  shadow_mark(color = "gray", size = 0.4) +
  geom_hline(yintercept = 0) +
  NULL -> anim


animate(
  anim, 
  nframes = 147, fps = 3, end_pause = 10
)

library(gganimate)
```

