---
title: "Netflix Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')  %>% 
  separate(duration, c("duration", "duration_units"), " ", convert = TRUE)



# Jeden Eintrag mehrfach listen für jede Kategorie einmal
netflix_titles %>% separate_rows(listed_in, sep = ", ")

# Jeden Eintrag mehrfach listen für jeden Schauspieler einmal
netflix_titles %>% separate_rows(cast, sep = ", ")


```






# Unsere Bearbeitung kommt hier hin

```{r}
```



# Ihre Bearbeitung kommt hier hin

```{r}
#Anzahl der veröffentlichten Filme & Serien im Vergleich
ggplot(netflix_titles, aes(x=type))+
  geom_bar() +
     labs(x= "Netflix type", y = "Amount of released movies & tv shows")

#Anzahl der veröffentlichten Filme ab 2005 (Balkendiagramm)
condition1 <- filter(netflix_titles, release_year >= 2005 & type == "Movie")
ggplot(condition1, aes(x=release_year, color=type))+
  geom_bar() +
    labs (x= "Release year", y = "Amount of released movies")

#Anzahl der veröffentlichten Filme & Serien ab 2010 im Vergleich (Liniendiagramm)
condition2 <- filter(netflix_titles, release_year >= 2010)
ggplot(condition2, aes(x=release_year, color=type))+
   geom_line(stat = 'count') +
      labs (x= "Release year", y = "Amount of released movies & tv shows")
```

