---
title: "exercise_03_VM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggridges)
library(psych)
library(gifski)
library(gganimate)
library(ggforce)
climate_data <- read_csv("datasets/climate_monthly.csv")

dat <- read_rds("datasets/lincoln_temps.rds")
```


```{r, include=FALSE}
data2 <- climate_data %>% 
  filter(Source == "GISTEMP") %>% 
  mutate(year = year(Date),
         month = month(Date))
```

```{r, Live Übung Sitzung 12.05.}

#Festsetzung eines themes übergeordnet für alle Viszalisierungen
theme_set(theme_light())

climate_data %>%
  filter(Source == "GISTEMP") %>%
  mutate(year = year(Date),
         month = month(Date)) %>%
         ggplot()+
         aes(x = month, y = Mean, color = Mean, group = year)+
         geom_line()+
         coord_polar()+
         scale_x_continuous(limits = c(0,12), breaks = 1:12)+
         geom_hline(yintercept = 0, color = "grey", size = 2)+
         scale_color_viridis_c(option = "B")+
         gganimate::transition_reveal(year)+
         labs(y = "Mean of global surface temperature change in   °C", subtitle = "development of mean global surface temperature change", title = "Temperature in the year:{frame_along}")->anim         
    
animate(
  anim,
  fps = 7,
  nframes = 137
  )
```

