---
title: "Exercise_02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(gganimate)
library(gifski)
library(gapminder)
library(hrbrthemes)
```


```{r}
gapminder %>% 
  filter(continent == "Asia") 

ggplot(gapminder, aes(x = lifeExp,y = pop, group = continent)) +
        geom_tile(aes(y = pop / 2, height = pop, fill = country), width = 0.9) +
        geom_text(aes(label = country), hjust = "right", colour = "black", fontface = "bold", nudge_y = -100000) +
        geom_text(aes(label = scales::comma(pop)), hjust = "left", nudge_y = 100000, colour = "grey30") +
        coord_flip(clip="off") +
        #scale_fill_manual(name = 'Country', values = c("#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3")) +
        scale_x_discrete("") +
        scale_y_continuous("",labels=scales::comma) +
        hrbrthemes::theme_ipsum(plot_title_size = 32, subtitle_size = 24, caption_size = 20, base_size = 20) +
        theme(panel.grid.major.y=element_blank(),
              panel.grid.minor.x=element_blank(),
              legend.position = c(0.4, 0.2),
              plot.margin = margin(1,1,1,2,"cm"),
              axis.text.y=element_blank()) +
        # gganimate code to transition by year:
        transition_time(year) +
        ease_aes('cubic-in-out') +
        labs(title='',
             subtitle='Population in {round(frame_time,0)}',
             caption='')
animate(p, nframes = 750, fps = 25, end_pause = 50, width = 1200, height = 900)
```

