---
title: "Visualisierung der Bundestagswahl 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# Daten laden
```{r}

parties <- c("CDU", "SPD")
perc_votes <- c(23.3, 12.4)

election <- data.frame(parties, perc_votes)

```


# Daten anpassen 
Daten werden gefiltert und sortiert
```{r}


```


Plots für das Bundesland generieren
```{r}

p <- election %>% ggplot()

```




# Visualisierung mit transparentem Hintergrund speichern
```{r}
p <- p +
  theme(
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent") # get rid of legend panel bg
  )
p

ggsave(p, filename = "ergebnis_NRW.png",  bg = "transparent")

```


# Automatisches Plotten mit geofacet
```{r}
# install.packages("geofacet")


csv_path <- "https://www.bundeswahlleiter.de/dam/jcr/72f186bb-aa56-47d3-b24c-6a46f5de22d0/btw17_kerg.csv"

library(geofacet)

read_csv2(csv_path, skip = 7) %>% filter(X3 == 99) %>% 
  select(land = X2, zweitstimmen = Endgültig_7,
         CDU = Endgültig_9,
         SPD = Endgültig_11,
         LINKE = Endgültig_13,
         GRUENE = Endgültig_15,
         CSU = Endgültig_17,
         FDP = Endgültig_19,
         AFD = Endgültig_21) %>% 
  pivot_longer(cols = -c(land, zweitstimmen)) %>% 
  group_by(land) %>% 
  mutate(prozent = value / zweitstimmen) -> votes


geofacet::get_grid_names()

votes %>% ggplot() +
  aes(x = prozent, y = "YY", fill = name) +
  scale_fill_manual(
    values = c(CDU = "#000000",
               SPD = "#FF0000", 
               LINKE = "#FF00FF",
               GRUENE = "#00FF00",
               CSU = "#000000",
               FDP = "#FFFF00",
               AFD = "#0088ff")) +
  geom_col() +
  coord_polar() +
  theme_void(8) +
  geofacet::facet_geo(grid = "de_states_grid1", vars(land))



```

