---
title: "Exercise_02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
climate_data <- read_csv("../../datasets/climate_monthly.csv")
```

```{r, include=FALSE}
climate_data %>% 
  filter(Source == "GISTEMP") %>% 
  mutate(year = year(Date),
         month = month(Date))
```


# Lösung
```{r}

library(ggforce)
climate_2000 <- filter(climate_data, year(Date) >= 2000 & year(Date) <= 2016)

ggplot(climate_2000, aes(x = year(Date), y = Mean, group = year(Date))) +
  geom_violin(fill = "skyblue", color = NA) +
  geom_sina(size = 0.75) +
    labs (title = "Temeraturvergleich der Jahre 2000-2016",
          subtitle = "Sina Plot",
          caption = "Höchsttemperaturen in 2016",
          x = "Jahr",
          y = "Sommermonate")
```

```{r}
# Live-Übung
ggplot(climate_data) +
aes(x = month(Date), y = Mean, color = Mean, group = year(Date)) +
geom_line() +
coord_polar() +
scale_x_continuous(limits = c(0,12), breaks = 1:12) +
geom_hline(yintercept = 0, color = "white", size = 2) +
scale_color_viridis_c(option = "D") +
gganimate::transition_reveal(year(Date)) +
labs(title = "Temperatur im Jahr: {frame_along}") -> anim

animate(
  anim,
  fps = 15,
  nframe = 137,
  renderer = gifski_renderer()
)
```

