---
title: "Live Übung 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

dat <- read_rds("../datasets/lincoln_temps.rds")
```

#Visualisierung aus Seminar
```{r}
ggplot(dat, aes(mean_temp, color = month))+
  geom_histogram(
    binwidth = 5,
    stat = "density"
  ) +
  labs(x = "Durchschnittstemperatur in Fahrenheit") +
  facet_wrap(~month)

```


```{r}
ggplot(dat, aes(mean_temp)) +
  geom_tile(
    aes(
      y = 1, 
      fill = after_stat(density)  
    ),
    stat = "density",
    n = 20    # number of points calculated by stat_density() 
  ) +
  labs(x = "Durchschnittstemperatur")
```


```{r}
ggplot(dat, aes(x = mean_temp)) +
geom_histogram(binwidth = 5, center = 2.5) +
  labs(x = "Durchschnittstemperatur")
```

#Hausaufgabe
```{r}
ggplot(dat, aes(month, mean_temp, fill = mean_temp)) +
  geom_tile(alpha = 0.9) +
  labs(x = "Monat", y = "Durchschnittstemperatur in Fahrenheit", title = "Hausaufgabe zum 12.05.2021: Im Juli 2016 kommt es in Lincoln zu den höchsten 
Temperaturen und im Dezember zu den niedrigsten", subtitle = "Vergleich der durchschnittlichen Temperaturen der Monate in Lincoln im Jahr 2016", caption = "Umrechnungsformel von Fahrenheit zu Celsius: 
Temperatur in °C = (Temperatur in °F − 32) / 1,8") +
  scale_fill_gradient(low = "blue", high = "red")
  
  
```

```{r}
RColorBrewer::display.brewer.all()
```

