---
title: "Exercise_02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(gganimate)
library(gifski)

climate_data <- read_csv("../datasets/climate_monthly.csv")
```


```{r, include=FALSE}
climate_data %>% 
  filter(Source == "GISTEMP") %>% 
  mutate(year = year(Date),
         month = month(Date))
```

```{r}
ggplot(climate_data, aes(x = Date, y = Mean, color = Source)) + 
  geom_line() +
  facet_wrap(~Source) +
  labs(x = "Jahr", y = "Durchschnitt", title = "Hausaufgabe zum 12.05.2021: Der GCAP und der GISTEMP sind in den letzten 
100 Jahren stetig angestiegen. Seit den 2010ern gibt es einen besonders starken 
Anstieg", subtitle = "Vergleich zwischen GCAG und GISTEMP von 1880 bis 2016", caption = "GCAG = Global component of Climate at a Glance 
       GISTEMP = Global Land-Ocean Temperature Index") +
  scale_color_manual(values=c("dark orange", "dark red")) +
  theme_bw()
```

```{r}
climate_data %>%
  filter(Source == "GISTEMP") %>%
  mutate(year = year(Date),
         month = month(Date)) %>%
         ggplot()+
         aes(x = month, y = Mean, color = Mean, group = year)+
         geom_line()+
         coord_polar()+
         scale_x_continuous(limits = c(0,12), breaks = 1:12)+
         geom_hline(yintercept = 0, color = "dark grey", size = 3)+
         scale_color_viridis_c(option = "C")+
         gganimate::transition_reveal(year)+
         labs(title = "Temperatur im Jahr:{frame_along}") -> anim
         animate(anim, fps = 4, nframes = 137)
```

