---
title: "exercise_02_homework_MK"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggridges)
library(psych)
library(ggforce)
climate_data <- read_csv("../datasets/climate_monthly.csv")

dat <- read_rds("../datasets/lincoln_temps.rds")
```


```{r, include=FALSE}
data2 <- climate_data %>% 
  filter(Source == "GISTEMP") %>% 
  mutate(year = year(Date),
         month = month(Date))
```

```{r, Ergebnis Livegruppenübung 5.5.21}

ggplot(dat, aes(x = mean_temp)) +
geom_histogram(binwidth = 5, center = 2.5) +
  labs(x = "Durchschnittstemperatur")


ggplot(dat, aes(mean_temp)) +
  geom_tile(
    aes(
      y = 1, 
      fill = after_stat(density)  
    ),
    stat = "density",
    n = 20    # number of points calculated by stat_density() 
  ) +
  labs(x = "Durchschnittstemperatur")

ggplot(dat, aes(mean_temp, color = month))+
  geom_histogram(
    binwidth = 5,
    stat = "density"
  ) +
   labs(x = "Durchschnittstemperatur")
```


```{r, Hausaufgaben 5.5.21 - 2 neue Visualisierunge}
#Zusammen erarbeitet mit VM 

#Festsetzung eines themes übergeordnet für alle Viszalisierungen
theme_set(theme_light())

#1. Visualisierung Lincoln Temperatures als Ridgeline Plot

describe(dat)

ggplot(dat, aes(x = mean_temp, y = month_long)) +
  geom_density_ridges(fill = "skyblue", color = "white") +
  labs(title = "The mean temperature in varied from -6 to 85 °F in 2016",
       x = "mean temperature (°F)",
       y = "",
       caption = "each month is visualized as a KDE",
       subtitle = "development of mean teamperatures Lincoln (Nebraska) in 2016")

#1. Visualisierung der Climate Data als Sina Plot

data2  %>%
  filter(year >= 2010) %>%
ggplot(aes(x = as.factor(year), y = Mean)) +
  geom_violin(fill = "skyblue", color = NA) + # violins in background
  geom_sina(size = 0.75) + # sina jittered points in foreground
  ylim(0, 1.4) +
  labs(title = "Temperature anomalies increased between 2010 and 2016 ",
       x = "",
       y = "Mean of global surface temperature change in °C",
       caption = "points indicate single measurements, violins show KDE",
       subtitle = "development of mean global surface temperature change")

```

```{r, Live-Übung 12.05.21 GIF}

library(gifski)
library(gganimate)

climate_data %>%
  filter(Source == "GISTEMP") %>%
  mutate(year = year(Date),
         month = month(Date)) %>%
         ggplot()+
         aes(x = month, y = Mean, color = Mean, group = year)+
         geom_line() +
         coord_polar() +
  scale_x_continuous(limits = c(0,12), breaks = 1:12)+
         geom_hline(yintercept = 0, color = "red", size = 1.5)+
         scale_color_viridis_c(option = "B")+
         gganimate::transition_reveal(year)+
  # Position zeigt die verschiedenen Jahre
         labs(title = "Temperatur im Jahr:{frame_along}") -> anim

animate(anim, fps = 4, nframes = 137)
# fps = Bilder pro Sekunde, hier werden 4 Linien = 4 Jahre pro Sekunde gezeichnet
# nframes = 137 entspricht der Anzahl der Jahre in dem Datensatz, wie viele einzelne Bilder werden insgesamt gezeichnet

```

