---
title: "Exercise 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(colorspace)
library(ggthemes)
library(patchwork)
```


```{r load_data}

# Filme von 1970 bis 2020, wenig Informationen pro Film
raw_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
# Filme von 1970 bis 2013, viele Informationen, viele Informationen pro Film

movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')
```

```{r}
movies %>%
  group_by(year) %>%
  filter(clean_test == "ok") %>%
  mutate(budget_med = median(budget)/1000000) %>%
  ggplot() +
    aes(x = year, y = budget_med) +
    geom_line(color = "chocolate2") +
  scale_y_continuous(limits = c(0, 70), breaks = c(0, 10, 20, 30, 40, 50, 60, 70)) +
  labs(title = "Filme mit der Bechdel-Bewertung 'ok'",
       x = "Jahr",
       y = "Budget (in Mio. €)") -> median_ok

movies %>%
  group_by(year) %>%
  filter(clean_test == "men") %>%
  mutate(budget_med = median(budget)/1000000) %>%
    ggplot() +
    aes(x = year, y = budget_med) +
    geom_line(color = "purple") +
    scale_y_continuous(limits = c(0, 70), breaks = c(0, 10, 20, 30, 40, 50, 60, 70)) +
  labs(title = "Filme mit der Bechdel-Bewertung 'men'", 
       x = "Jahr",
       y = "Budget (in Mio. €)") -> median_men

median_ok + median_men +
  plot_annotation(title = "Ab ca. 1990 haben Filme mit der Bechdel-Bewertung 'men' ein höheres Budget als\nFilme mit der Bechdel-Bewertung 'ok'", 
                  subtitle = "Median der Budgethöhe von Filmen mit der Bechdel-Bewertung von 'ok' bzw. 'men' von 1970 bis 2013")

```

```{r}
movies %>%
  filter(clean_test == "ok") %>%
  ggplot() +
    aes(x = year, y = budget/1000000) +
    geom_point(alpha = 0.3, color = "red") +
  scale_y_continuous(limits = c(0, 425)) +
  labs(title = "Budgethöhe der Filme mit der\nBechdel-Bewertung 'ok'\nvon 1970 bis 2013", 
       y = "Budget (in Mio.)") -> budget_ok

movies %>%
  filter(clean_test == "men") %>%
  ggplot() +
    aes(x = year, y = budget/1000000) +
    geom_point(alpha = 0.3, color = "blue") +
    scale_y_continuous(limits = c(0, 425)) +
  labs(title = "Budgethöhe der Filme mit der\nBechdel-Bewertung 'men'\nvon 1970 bis 2013", 
       y = "Budget (in Mio.)") -> budget_men

budget_ok + budget_men
```
