---
title: "05_probieren"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggforce)
library(geofacet)
```

# Daten laden
```{r echo = T, results = 'hide'}
get_grid_names()

csv_path <- "https://www.bundeswahlleiter.de/dam/jcr/72f186bb-aa56-47d3-b24c-6a46f5de22d0/btw17_kerg.csv"

read_csv2(csv_path, skip = 7) %>% 
  filter(X3 == 99) %>% 
  select(land = X2, zweitstimmen = Endgültig_7,
         CDU = Endgültig_9,
         SPD = Endgültig_11,
         LINKE = Endgültig_13,
         GRUENE = Endgültig_15,
         CSU = Endgültig_17,
         FDP = Endgültig_19,
         AFD = Endgültig_21) %>% 
  pivot_longer(cols = -c(land, zweitstimmen)) %>% 
  group_by(land) %>% 
  mutate(prozent = value / zweitstimmen) %>% 
  na.omit() -> votes
```

# Daten anpassen
```{r} 
pie_data <- votes %>%
  mutate(prozent = round(prozent, 3) * 100) %>%
  arrange(prozent) %>% # sort so pie slices end up sorted
  mutate(
    end_angle = 2*pi*cumsum(prozent)/sum(prozent),   # ending angle for each pie slice
    start_angle = lag(end_angle, default = 0),   # starting angle for each pie slice
    mid_angle = 0.5*(start_angle + end_angle),   # middle of each pie slice, for text labels
    # horizontal and vertical justifications for outer labels
    hjust = ifelse(mid_angle > pi, 1, 0),
    vjust = ifelse(mid_angle < pi/2 | mid_angle > 3*pi/2, 0, 1)
  ) 

```

# Plots für Bundesländer generieren und speichern
```{r}
# Baden-Württemberg
p <- pie_data %>% 
  filter(land == "Baden-Württemberg") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_BaWü.png",  bg = "transparent")

# Bayern
p <- pie_data %>% 
  filter(land == "Bayern") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Bayern.png",  bg = "transparent")

# Berlin
p <- pie_data %>% 
  filter(land == "Berlin") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Berlin.png",  bg = "transparent")

# Brandenburg
p <- pie_data %>% 
  filter(land == "Brandenburg") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Brandenburg.png",  bg = "transparent")

# Bremen
p <- pie_data %>% 
  filter(land == "Bremen") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "white", "black"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Bremen.png",  bg = "transparent")

# Hamburg
p <- pie_data %>% 
  filter(land == "Hamburg") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Hamburg.png",  bg = "transparent")

# Hessen
p <- pie_data %>% 
  filter(land == "Hessen") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Hessen.png",  bg = "transparent")

# Mecklenburg-Vorpommern
p <- pie_data %>% 
  filter(land == "Mecklenburg-Vorpommern") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Mecklenburg-Vorpommern.png",  bg = "transparent")

# Niedersachsen
p <- pie_data %>% 
  filter(land == "Niedersachsen") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Niedersachsen.png",  bg = "transparent")

# Nordrhein-Westfalen
p <- pie_data %>% 
  filter(land == "Nordrhein-Westfalen") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Nordrhein-Westfalen.png",  bg = "transparent")

# Rheinland-Pfalz
p <- pie_data %>% 
  filter(land == "Rheinland-Pfalz") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Rheinland-Pfalz.png",  bg = "transparent")

# Saarland
p <- pie_data %>% 
  filter(land == "Saarland") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Saarland.png",  bg = "transparent")

# Sachsen
p <- pie_data %>% 
  filter(land == "Sachsen") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "white", "black"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Sachsen.png",  bg = "transparent")

# Sachsen-Anhalt
p <- pie_data %>% 
  filter(land == "Sachsen-Anhalt") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Sachsen-Anhalt.png",  bg = "transparent")

# Schleswig-Holstein
p <- pie_data %>% 
  filter(land == "Schleswig-Holstein") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Schleswig-Holstein.png",  bg = "transparent")

# Thüringen
p <- pie_data %>% 
  filter(land == "Thüringen") %>%
  ggplot() +
  aes(
    x0 = 0, y0 = 0, r0 = 0.4, r = 1,
    start = start_angle, end = end_angle,
    fill = name
  ) +
  geom_arc_bar() +
  geom_label( # place amounts inside the pie
    aes(
      x = 0.7 * sin(mid_angle),
      y = 0.7 * cos(mid_angle),
      label = paste0(prozent, "%"),
      fill = name
    ),
    color = c("black", "black", "black", "black", "black", "white"), 
    fontface = "bold"
  ) +
  geom_text( # place party name outside the pie
    aes(
      x = 1.05 * sin(mid_angle),
      y = 1.05 * cos(mid_angle),
      label = name,
      hjust = hjust, vjust = vjust
    )
  ) +
  coord_fixed(xlim = c(-1.8, 1.3)) +
  scale_fill_manual(values = c(CDU = "#0C0C0C",
               SPD = "#E4000F", 
               LINKE = "#E90098",
               GRUENE = "#65A22C",
               CSU = "#0C0C0C",
               FDP = "#FFFD01",
               AFD = "#009DE0")) + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        axis.text = element_blank(),
        legend.position = "none",
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"))

ggsave(p, filename = "ergebnis_Thüringen.png",  bg = "transparent")
```

